// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvAxr8KlOdyLITYGTZG8ZBRrtV7fYPlX8',
    appId: '1:120037539386:web:26117cb837e71186c97f03',
    messagingSenderId: '120037539386',
    projectId: 'spotify-all-songs-playlist',
    authDomain: 'spotify-all-songs-playlist.firebaseapp.com',
    storageBucket: 'spotify-all-songs-playlist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IX9SJH1neVEbKaS7dbFws4WriUZEV0c',
    appId: '1:120037539386:android:df85d011a4fc005ec97f03',
    messagingSenderId: '120037539386',
    projectId: 'spotify-all-songs-playlist',
    storageBucket: 'spotify-all-songs-playlist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC9_tqggmVZzXDm7razB55vyj34lw90_g',
    appId: '1:120037539386:ios:f7b6552d03d56407c97f03',
    messagingSenderId: '120037539386',
    projectId: 'spotify-all-songs-playlist',
    storageBucket: 'spotify-all-songs-playlist.appspot.com',
    iosClientId: '120037539386-g9eq00gqfjen7dvgd3ktlo7sut06k0fd.apps.googleusercontent.com',
    iosBundleId: 'com.mlmorgan.spotify-all-songs-playlist',
  );
}
