// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUAJM9kDtfCk3V-g3MQQxoKRmWq4q4BQ',
    appId: '1:224795479664:android:7e4f57cabd939106222eb5',
    messagingSenderId: '224795479664',
    projectId: 'spotify-all-songs-playli-6c572',
    storageBucket: 'spotify-all-songs-playli-6c572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW1FKSYqwf0yBWPOX8SKSPuoEkP5_vGtc',
    appId: '1:224795479664:ios:2b7ed0495b7735ec222eb5',
    messagingSenderId: '224795479664',
    projectId: 'spotify-all-songs-playli-6c572',
    storageBucket: 'spotify-all-songs-playli-6c572.appspot.com',
    iosClientId: '224795479664-scls7cmtqbvekrj4los4a60hvrtfhav2.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyAllSongsPlaylist',
  );
}
